# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-pin-service:
    image: mongo:4.2.0
    container_name: mongo-pin-service
    ports:
      - '5555:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs:
    # https://github.com/christroutner/trickle-ipfs
    image: christroutner/trickle-ipfs:v1.0.1
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    container_name: ipfs
    environment:
      IPFS_DAEMON_ARGUMENTS: '--enable-pubsub-experiment --migrate=true --agent-version-suffix=docker --routing=dhtclient --enable-gc'
      UPLOAD_KBPS: '1000'
      DOWNLOAD_KBPS: '1000'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 2000mb
    ports:
      - 4001:4001
      - 4003:4003
      - 172.17.0.1:5001:5001
      - 8080:8080
    command: [
      './start-ipfs.sh'
    ]
    volumes:
      - ../data/go-ipfs/data:/root/.ipfs
    restart: always

  p2wdb:
    #build:
    #  context: ./p2wdb/
    #  dockerfile: Dockerfile
    image: christroutner/p2wdb:v3.3.1
    container_name: p2wdb
    environment:
      CONSUMER_URL: 'https://free-bch.fullstack.cash'
      DEBUG_LEVEL: 1
      #ENABLE_BCH_PAYMENT: 1
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1gb
    links:
      - mongo-pin-service
      - ipfs
    ports:
      # <host port>:<container port>
      - 5667:5667 # REST API
      #- 5668:5668 # IPFS TCP port
      #- 5669:5669 # IPFS WS Port
    volumes:
      - ../data/ipfsdata/p2wdb:/home/safeuser/ipfs-p2wdb-service/.ipfsdata/p2wdb
      - ./p2wdb/start-production.sh:/home/safeuser/ipfs-p2wdb-service/start-production.sh
      #- ../../wallet.json:/home/safeuser/ipfs-p2wdb-service/wallet.json
    restart: always

  # (Optional) This contain can be commented out. It provides v1 Circuit Relay
  # services for creating tunnels through firewalls and passing files through
  # them.
  circuit-relay-v1:
    #build: .
    image: christroutner/circuit-relay-v1:v1.0.0
    container_name: circuit-relay-v1
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1gb
    environment:
      MY_ENV_VAR: 'placeholder'
    #links:
    #  - p2wdb-mongodb
    ports:
      # <host port>:<container port>
      - 4102:4102 # TCP
      - 4103:4103 # Websockets
    volumes:
      - ./v1-relay/relay-config:/root/go/bin/relay-config
    restart: always

  pin-service:
    #build: ./pin-service/
    image: christroutner/p2wdb-pin-service:v2.0.7
    container_name: pin-service
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 500mb
    links:
      - mongo-pin-service
      - p2wdb
    ports:
      - '5010:5010' # <host port>:<container port>
    volumes:
      - ./pin-service/start-production.sh:/home/safeuser/p2wdb-pinning-service/start-production.sh
    restart: always
