# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-pin-service:
    image: mongo:4.2.0
    container_name: mongo-pin-service
    ports:
      - '5555:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs:
    image: ipfs/go-ipfs:v0.14.0
    container_name: ipfs
    environment:
      MY_ENV_VAR: 'placeholder'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 2000mb
    ports:
      - 4001:4001
      - 172.17.0.1:5001:5001
      - 172.17.0.1:8080:8080
    volumes:
      - ../data/go-ipfs/data:/data/ipfs
      #- ../../swarm.key:/data/ipfs/swarm.key
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#command
    # https://github.com/ipfs/go-ipfs/blob/91c52657166bcf86f2476926e4fe56694dc26562/Dockerfile#L115
    command:
      [
        'daemon',
        '--migrate=true',
        '--agent-version-suffix=docker',
        '--enable-pubsub-experiment'
      ]
    restart: always

  p2wdb:
    #build:
    #  context: ./p2wdb/
    #  dockerfile: Dockerfile
    image: christroutner/p2wdb:v3.0.6
    container_name: p2wdb
    environment:
      CONSUMER_URL: 'https://free-bch.fullstack.cash'
      DEBUG_LEVEL: 1
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1gb
    links:
      - mongo-pin-service
      - ipfs
    ports:
      # <host port>:<container port>
      - 5667:5667 # REST API
      #- 5668:5668 # IPFS TCP port
      #- 5669:5669 # IPFS WS Port
    volumes:
      - ../data/ipfsdata/p2wdb:/home/safeuser/ipfs-p2wdb-service/.ipfsdata/p2wdb
      - ./p2wdb/start-production.sh:/home/safeuser/ipfs-p2wdb-service/start-production.sh
    restart: always

  pin-service:
    build: ./pin-service/
    #image: christroutner/ipfs-service-provider:v2.2.1
    container_name: pin-service
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 500mb
    links:
      - mongo-pin-service
      - p2wdb
    ports:
      - '5010:5010' # <host port>:<container port>
    volumes:
      - ./pin-service/start-production.sh:/home/safeuser/p2wdb-pinning-service/start-production.sh
    restart: always
